language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

# branches:
#   only:
#     - master

install:
  - npm install -g vuepress

  script:
  - npm run docs:build

  deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local-dir: docs/.vuepress/dist
